### model
model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct
image_max_pixels: 12845056
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 32
lora_alpha: 128
lora_dropout: 0.05
lora_target: all
freeze_vision_tower: false  # choices: [true, false]
freeze_multi_modal_projector: false  # choices: [true, false]
#deepspeed: /jinru/VLM-R1/src/open-r1-multimodal/local_scripts/zero2.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: percive_sft_train
template: qwen2_vl
cutoff_len: 131072
overwrite_cache: true
preprocessing_num_workers: 8

### output
output_dir: /jinru/saves/qwen2_5_vl-3b-sft/percive
logging_steps: 10
save_steps: 50
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 16
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
